baseurl = "/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  contentTypeName = "post"
  themeColor = "red"
  showMenuItems = 4
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    title = "D&D Adventures"
    subtitle = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Dungeons & Dragons"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "map"
        name = "Map"
        url = "/map"
      [[languages.en.menu.main]]
        identifier = "post"
        name = "Our Story"
        url = "/post"  
      [[languages.en.menu.main]]
        identifier = "resources"
        name = "Resources"
        url = "/resources"
